### ISSUE TITLE
Generate srt?

### ISSUE THREAD

**Issue by ltworf** [dsymbol/decipher#1]
Hello,

This is very similar to something I was planning to do.

Wouldn't it be better to generate .srt files instead? So one can manually adjust the errors, fix the size, disable them and so on.

If you want a single file you can separately make a .mkv file and add a subtitle track.

**Comment by dsymbol** [comment]
It generates srt files by default I just feel like the main point of this script is burning them in, to force them.

Feel free to fork and create your own version of it though.

Edit: on second thought adjusting the errors does sound like a very important feature I might to implement this as a cli argument, something like --no-burn

**Comment by ltworf** [comment]
Yeah well I've started to implement my own.

I've realised it's good only for a rough initial version but needs manual fixing.

https://github.com/ltworf/srtgen
