### ISSUE TITLE
Please add s static-ffmpg to provide binaries

### ISSUE THREAD

**Issue by zackees** [dsymbol/decipher#13]
You can use 
from static_ffmpef import add_paths
add_paths(weak=True)

To add ffmpeg to your project that will download platform specific ffmpeg for this package if ffmpeg is not already on the system path.

My own package 'transcribe-anything' does this to great effect.

**Comment by dsymbol** [comment]
Thanks for the suggestion but I've already implemented it myself as I didn't know of static_ffmpeg's existence.
