### ISSUE TITLE
Conversion failed!

### ISSUE THREAD

**Issue by 709689175** [dsymbol/decipher#20]
When I was burning generated subtitles into video, an error occurred, prompting me' Conversion failed!' The generated mp4 file is 0kb

**Comment by 709689175** [comment]
Converting `SubRip Subtitle file` to `Advanced SubStation Alpha file`
zcr_test_16925971879458.srt: 9 seconds [00:00, 17831.24 seconds/s]
Burning `Advanced SubStation Alpha file` into zcr_test_16925971879458.mp4...
Conversion failed!

**Comment by dsymbol** [comment]
Could you try this [file](https://github.com/ietf-wg-cellar/matroska-test-files/blob/master/test_files/test2.mkv) and tell me if it works?

**Comment by 709689175** [comment]
I used the command "Burn generated subtitles into video:" to try to combine the mp4 file with the corresponding srt file. The MP4 file is valid, but the resulting MP4 file is invalid because it has a memory of 0kb.

**Comment by dsymbol** [comment]
Is this the command you ran? if so did you make sure the original mp4 and the srt file were in the same directory?
```
decipher subtitle -i "zcr_test_16925971879458.mp4" --subtitle_file "zcr_test_16925971879458.srt" --subtitle_action burn
```
Please send me the full log

**Comment by 709689175** [comment]
`python -m decipher subtitle -i /home/aigc/AIGC/LiveStorage/test/zcr/8022/zcr_test_16926685441020.mp4 --subtitle_file /home/aigc/AIGC/LiveStorage/subtitle/loding/test2.srt --subtitle_action burn -o /home/aigc/AIGC/api/subtitle_api/result/`
I used the absolute path.

**Comment by 709689175** [comment]
`Converting 'SubRip Subtitle file' to 'Advanced SubStation Alpha file'

test2.srt: 9 seconds [00:00, 37374.99 seconds/s]

Burning 'Advanced SubStation Alpha file' into zcr_test_16926685441020.mp4...

Conversion failed!

Output -> /home/aigc/AIGC/api/subtitle_api/result`

**Comment by 709689175** [comment]
I use Ubuntu

**Comment by dsymbol** [comment]
Ran the same command on Debian 11 with no problem, can you try a different mp4 file?

**Comment by santiverdi** [comment]
Hi bro, can you help me please? I don't know what I'm doing wrong. Here what I did. Sorry bothering you, Im new.
![image](https://github.com/dsymbol/decipher/assets/105940458/f4124ab9-e714-4524-8372-a9c619ed57b7)

**Comment by santiverdi** [comment]
got it bro, de file directory was wrong. thanks for such a good ia!
