### ISSUE TITLE
Could not write header (incorrect codec parameters ?): Invalid argument

### ISSUE THREAD

**Issue by DuckersMcQuack** [dsymbol/decipher#22]
Tried to transcribe an episode of the rookie

Input #0, matroska,webm, from 'C:\Users\Duckers\Downloads\rookie.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
  Duration: 00:43:03.65, start: 0.000000, bitrate: 10197 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 9555108
      DURATION        : 00:43:03.623000000
      NUMBER_OF_FRAMES: 61945
      NUMBER_OF_BYTES : 3085849879
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      BPS             : 640000
      DURATION        : 00:43:03.648000000
      NUMBER_OF_FRAMES: 80739
      NUMBER_OF_BYTES : 206691840
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      BPS             : 105
      DURATION        : 00:42:58.507000000
      NUMBER_OF_FRAMES: 1178
      NUMBER_OF_BYTES : 34122
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip (hearing impaired)
    Metadata:
      title           : SDH
      BPS             : 113
      DURATION        : 00:42:58.507000000
      NUMBER_OF_FRAMES: 1299
      NUMBER_OF_BYTES : 36505
      _STATISTICS_WRITING_APP: mkvmerge v74.0.0 ('You Oughta Know') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[adts @ 0000026a2c79e600] Only AAC streams can be muxed by the ADTS muxer
[out#0/adts @ 0000026a2c785c80] Could not write header (incorrect codec parameters ?): Invalid argument
Error opening output file rookie.aac.
Error opening output files: Invalid argument

**Comment by dsymbol** [comment]
Should work now.
