### ISSUE TITLE
2 issues on macos / apple silicon

### ISSUE THREAD

**Issue by gregsadetsky** [dsymbol/decipher#23]
thanks a lot for this tool!!

I installed it by manually git cloning the repo, and running `pip3 install .`

the first error I received was:

`TypeError: WhisperForConditionalGeneration.__init__() got an unexpected keyword argument 'attn_implementation'`

I "fixed" it by removing `model_kwargs={"attn_implementation": "sdpa"},` from [this line](https://github.com/dsymbol/decipher/blob/main/decipher/action.py#L42) in action.py

the next problem I encountered was `AttributeError: module 'torch' has no attribute 'mps'`

I "fixed" that one by commenting out [these lines](https://github.com/dsymbol/decipher/blob/main/decipher/action.py#L45,L46) in the same file

and then everything worked and I was able to burn the subtitles into the video file! :-) woo

if it helps, I'm using Python 3.11.2 on macos 12.7

thanks again!

**Comment by dsymbol** [comment]
Glad you're enjoying it, I don't have a Mac I'm going based off of https://github.com/Vaibhavs10/insanely-fast-whisper/blob/main/src/insanely_fast_whisper/cli.py#L102 I can't find the error you're experiencing anywhere in his repo. could you try his implementation and let me know how it goes?
