### ISSUE TITLE
"CPU is being used for this transcription, this process may take a while."

### ISSUE THREAD

**Issue by GoldstarZV** [dsymbol/decipher#25]
I'm getting a message during the process
`CPU is being used for this transcription, this process may take a while.` 
any way to force it to use GPU? I'm running a 4090, I've got the right CUDA stuff installed already, etc.

**Comment by dsymbol** [comment]
Run these and try again:

```bash
pip3 uninstall torch -y
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```
