### ISSUE TITLE
Issue with burn subtitle

### ISSUE THREAD

**Issue by chienhao10** [dsymbol/decipher#26]
This tool is great and thx for this, I don't have to install all the stuff and run it on colab for srt generation.
After i got text generated, I tried to Burn in to video. No matter use the Burn in "Transcript" or "Subtitle", I will get below attached result. It seems I am missing the font file?
My text strings are in Chinese
![error](https://github.com/dsymbol/decipher/assets/10517772/7fcca1b6-085c-4ccf-a11e-62a765ce8ee4)

Some text got generated and try to burn in:
`1
00:00:00,720 --> 00:00:02,000
哈囉大家好我是品哥

2
00:00:02,000 --> 00:00:04,400
今天又來到了大家最喜歡的單元

3
00:00:04,400 --> 00:00:06,599
麥當勞新品開箱

4
00:00:06,599 --> 00:00:08,699
這次我要開箱的第一個是

5
00:00:08,699 --> 00:00:10,500
熬龍蝦堡`

Another question is what does "Add" do? I thought this will add generated string in to video, but I actually don't see anything been added. Only "Burn" will have different outcome.

**Comment by dsymbol** [comment]
Can't reproduce works for me on a random Chinese video, about "Add" it simply doesn't burn it into the video but adds it instead so that it can be disabled if unwanted. in vlc: `Subtitle -> Sub Track`
