### ISSUE TITLE
Disturbing Subs....

### ISSUE THREAD

**Issue by m0nd0CH1CK3N** [dsymbol/decipher#27]
Some of the generated subtitles are, "I'm going to kill you." This happens when there is no dialogue or when there is some discordant moaning. There are also some errors with the moaning over dialogue, but these are less of a concern.

It is easy to change the subtitle text before burning, but I find this error disturbing.

I changed language='english' because there was an error with having multiple language in ln. 1169. I was using the large-v2 model.
<img width="1280" alt="Macbeth (1979 - Scary Subs" src="https://github.com/dsymbol/decipher/assets/69602947/6f76cfc8-75f9-4f96-9228-d0c5797454be">

**Comment by anupamkumar** [comment]
lol. No one said ML is perfect.

**Comment by dsymbol** [comment]
These are [whisper](https://github.com/openai/whisper) related issues.
