### ISSUE TITLE
transcribe and translate

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [dsymbol/decipher#29]
is there a chance to translate X->X for --task?
something like
decipher transcribe -i input.mp4 --language-from en --language-to es --model small --task translate
thanks

**Comment by anupamkumar** [comment]
check out https://github.com/anupamkumar/subtitler @ROBERT-MCDOWELL

**Comment by dsymbol** [comment]
whisper only supports translation from X->English sorry.
