### ISSUE TITLE
Error on transcribe on Macbook M1

### ISSUE THREAD

**Issue by hamisus** [dsymbol/decipher#3]
Running `decipher transcribe -i E02.mp4 --model small` results in an error:

`(base) adam@192 decipher % decipher transcribe -i E02.mp4 --model small
Extracting audio file...
Traceback (most recent call last):
  File "/Users/adam/opt/anaconda3/bin/decipher", line 8, in <module>
    sys.exit(main())
  File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/__main__.py", line 92, in main
    transcribe(
  File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/decipher.py", line 18, in transcribe
    run(
  File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/decipher.py", line 83, in run
    p = subprocess.run(command, text=True)
  File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -y -i /Users/adam/Git/decipher/E02.mp4 -vn -acodec copy E02.aac'`

Running on MacBook Pro M1

**Comment by dsymbol** [comment]
> Running `decipher transcribe -i E02.mp4 --model small` results in an error:
> 
> `(base) adam@192 decipher % decipher transcribe -i E02.mp4 --model small Extracting audio file... Traceback (most recent call last): File "/Users/adam/opt/anaconda3/bin/decipher", line 8, in <module> sys.exit(main()) File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/__main__.py", line 92, in main transcribe( File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/decipher.py", line 18, in transcribe run( File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/decipher/decipher.py", line 83, in run p = subprocess.run(command, text=True) File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 505, in run with Popen(*popenargs, **kwargs) as process: File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/Users/adam/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -y -i /Users/adam/Git/decipher/E02.mp4 -vn -acodec copy E02.aac'`
> 
> Running on MacBook Pro M1

Hey, can you follow [this](https://www.youtube.com/watch?v=nmrjRqEIgGc) tutorial and try running the same command again?
