### ISSUE TITLE
Love it but I can't code a line..Hopefully for a GUI for mac

### ISSUE THREAD

**Issue by shruru** [dsymbol/decipher#4]
REally love the idea. however for newbie like me, We prefer a GUI to run it. :P , Is it possible? (if you need design help, feel free to contact me )

Thank you!

**Comment by dsymbol** [comment]
I don't really have the time to create a GUI however the cli interface is rather simple, do you need help with a specific command?

**Comment by shruru** [comment]
Thanks for prompt reply. yep, I wanna batch export / generate SRT from videos. is it possible? Such as a TV show etc. BTW I also don't know how to do it on MacOS even the command line. by using the "terminal"?

**Comment by dsymbol** [comment]
Yes the terminal, I'd recommend you look up tutorials on how to use it online before attempting to use this program.

**Comment by shruru** [comment]
Thanks, any tutorial links please? I typed "$ pip install git+https://github.com/dsymbol/decipher" in Terminal, got the error message.

**Comment by Orphillus** [comment]
I dont think it woud be too difficult to use tkinter or pyqt5 to make a partial gui with this
