### ISSUE TITLE
Not really a critical issue but im getting this error.

### ISSUE THREAD

**Issue by Orphillus** [dsymbol/decipher#8]
So I have a 3060 and a core i9-12900kf and when im using decipher im getting the error:  UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
but also this software is absoultely amazing you have done an absolutely amazing job

**Comment by dsymbol** [comment]
Had the same problem, it means torch is using the CPU (slower) instead of the GPU following this fixed it for me:
https://github.com/openai/whisper/discussions/47#discussioncomment-3713334

**Comment by Orphillus** [comment]
> Had the same problem, it means torch is using the CPU (slower) instead of the GPU following this fixed it for me: [openai/whisper#47 (comment)](https://github.com/openai/whisper/discussions/47#discussioncomment-3713334)

youre freaking amazing

**Comment by Orphillus** [comment]
> 

Lol i just applied the fix and it went from rendering a video in 3/4 mins in about 15 seconds
