### ISSUE TITLE
 Is it possible to provide a function to trim the video according to the modification of the subtitle file

### ISSUE THREAD

**Issue by appleatiger** [dsymbol/decipher#9]
Generally, when making a video, it is often encountered that the narration is not coherent, so it is often necessary to delete the meaningless part. If the video can be edited according to the generated subtitle file, it will greatly reduce the playback time of the video. That is going to be a really useful tool.

**Comment by dsymbol** [comment]
Not currently planned as I think its niche.

However you can use the ffmpeg command-line tool to cut a video from a start timestamp to an end timestamp using the -ss and -to options. Here's an example command that cuts a video from the 5 minute mark to the 10 minute mark:

```bash
ffmpeg -i input.mp4 -ss 00:05:00 -to 00:10:00 -c copy output.mp4
```
